name: bnn
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.2+14

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  dio: ^5.7.0
  flutter_material_pickers: ^3.7.0
  file_picker: ^8.1.4
  file_saver: ^0.2.14
  choice: ^2.3.2
  country_picker: ^2.0.27
  country_icons: ^3.0.0
  country_flags: ^3.1.0
  image_picker: ^1.1.2
  supabase_flutter: ^2.8.3
  google_sign_in: ^6.2.2
  permission_handler: ^11.3.1
  shared_preferences: ^2.3.5
  skeletonizer: ^1.4.3
  flutter_supabase_chat_core: ^1.4.3
  flutter_chat_types: ^3.6.2
  infinite_scroll_pagination: ^4.1.0
  timeago: ^3.7.0
  path_provider: ^2.1.5
  http: ^1.2.2
  flutter_chat_ui: ^1.6.15
  get_thumbnail_video: ^0.7.3
  cube_transition_plus: ^2.0.1
  flutter_styled_toast: ^2.2.1
  flutter_dotenv: ^5.2.1
  provider: ^6.1.2
  open_filex: ^4.6.0
  video_player: ^2.9.3
  google_sign_in_ios: ^5.8.1
  twilio_flutter: ^0.9.0
  phone_numbers_parser: ^9.0.3


dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - .env
    - assets/images/
    - assets/images/icons/
    - assets/images/post/ 
    - assets/images/avatar/
    - assets/images/live/
    - assets/images/profile/
    - assets/images/settings/

  fonts:
  - family: Archivo
    fonts:
      - asset: assets/fonts/Archivo-Bold.ttf
      - asset: assets/fonts/Archivo-BoldItalic.ttf
      - asset: assets/fonts/Archivo-Italic.ttf
      - asset: assets/fonts/Archivo-Medium.ttf
      - asset: assets/fonts/Archivo-Regular.ttf
      - asset: assets/fonts/Archivo-SemiBold.ttf
        # weight: FontWeight.w700

  - family: Poppins
    fonts:
      - asset: assets/fonts/Poppins-Black.ttf
      - asset: assets/fonts/Poppins-Bold.ttf
      - asset: assets/fonts/Poppins-ExtraBold.ttf
      - asset: assets/fonts/Poppins-ExtraLight.ttf
      - asset: assets/fonts/Poppins-Light.ttf
      - asset: assets/fonts/Poppins-Medium.ttf
      - asset: assets/fonts/Poppins-Regular.ttf
      - asset: assets/fonts/Poppins-SemiBold.ttf
      - asset: assets/fonts/Poppins-Thin.ttf

  - family: Nunito
    fonts:
      - asset: assets/fonts/Nunito-VariableFont_wght.ttf  
      - asset: assets/fonts/Nunito-Bold.ttf  
      - asset: assets/fonts/Nunito-Black.ttf  
      - asset: assets/fonts/Nunito-ExtraBold.ttf  
      - asset: assets/fonts/Nunito-Light.ttf  
      - asset: assets/fonts/Nunito-Medium.ttf  
      - asset: assets/fonts/Nunito-SemiBold.ttf  
      - asset: assets/fonts/Nunito-Regular.ttf  

